coin-families:
  - name: ETH
    correlated: true
    coin-list:
      - ETH
      - WETH
      - BETH
      - WBETH
      - STETH
      - WSTETH
      - RETH
      - RSETH
      - METH
      - LSETH
      - EZETH
      - ETHX
      - TETH
      - ETH+
      - OETH
      - SWETH
      - AGETH
      - VBETH
      - ROCK.RETH
      - ANKRETH
      - NETH
      - ETHA
      - YNETHX
      - CRVSTETH
      - ETH0
      - ATETH
      - CBETH
      - GTETH
      - EZETH   
  - name: USD
    correlated: true
    coin-list:
      - USDC
      - USDT
      - DAI
      - USDS
      - USDE
      - GHO
      - RLUSD
      - SUSDS
      - CRVUSD
      - sCRVUSD
      - sUSDe
    regexp-rule: ".*USD.*"

  - name: EUR
    correlated: true
    coin-list:
      - EURC
      - EURI
      - EURCV
      - EURQ

  - name: GOLD
    correlated: true
    coin-list:
      - PAXG
      - XAUT

  - name: BTC
    correlated: true
    coin-list:
      - BTC
      - WBTC
      - CBBTC
      - tBTC
      - FBTC
      - LBTC
      - kBTC

  - name: SOL
    correlated: true
    coin-list:
      - SOL
      - mSOL

  - name: AAVE
    correlated: true
    coin-list:
      - AAVE
      - STKAAVE

  - name: Tier1
    correlated: false
    sql-rule: "cmc_rank < 100"
    include-coin:
      - PENDLE 
      - ENA