-- Create the data warehouse database
CREATE DATABASE chaintelligence;

-- Switch to the new database to create tables
\c chaintelligence;

-- 1. COIN TABLE (coin_id as PK, symbol as VARCHAR(10) UNIQUE)
CREATE TABLE IF NOT EXISTS coin (
    coin_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(255),
    slug VARCHAR(255),
    hardness INTEGER DEFAULT 0,
    cmc_rank INTEGER,
    cmc_id INTEGER UNIQUE,
    first_historical_data TIMESTAMP WITH TIME ZONE,
    image_url TEXT,
    price NUMERIC,
    price_timestamp TIMESTAMP WITH TIME ZONE,
    decimals INTEGER DEFAULT 18,
    percent_change_1h NUMERIC,
    percent_change_24h NUMERIC,
    percent_change_7d NUMERIC,
    percent_change_30d NUMERIC,
    percent_change_60d NUMERIC,
    percent_change_90d NUMERIC,
    market_cap NUMERIC,
    market_cap_dominance NUMERIC,
    fully_diluted_market_cap NUMERIC,
    tvl NUMERIC,
    total_supply NUMERIC,
    circulating_supply NUMERIC,
    max_supply NUMERIC,
    cmc_last_updated TIMESTAMP WITH TIME ZONE
);

-- 1.2 COIN CONTRACT TABLE (Multi-chain contract address mapping)
CREATE TABLE IF NOT EXISTS coin_contract (
    coin_id SMALLINT NOT NULL REFERENCES coin(coin_id) ON DELETE CASCADE,
    chain VARCHAR(20) NOT NULL,
    contract_address VARCHAR(64) NOT NULL,
    decimals INTEGER DEFAULT 18,
    is_native BOOLEAN DEFAULT FALSE,
    verified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (coin_id, chain)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_coin_contract_addr ON coin_contract (chain, LOWER(contract_address));
CREATE INDEX IF NOT EXISTS idx_coin_contract_chain ON coin_contract (chain);

-- Trigger to lowercase contract_address
CREATE OR REPLACE FUNCTION lowercase_contract_address() 
RETURNS TRIGGER AS $$
BEGIN
  NEW.contract_address = LOWER(NEW.contract_address);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_coin_contract_address_lower
BEFORE INSERT OR UPDATE ON coin_contract
FOR EACH ROW EXECUTE FUNCTION lowercase_contract_address();

-- Index for case-insensitive lookup (though we force upper)
CREATE UNIQUE INDEX IF NOT EXISTS coin_symbol_idx ON coin (UPPER(symbol));

-- 1.5 COIN FAMILY TABLE
CREATE TABLE IF NOT EXISTS coin_family (
    name VARCHAR(50) NOT NULL,
    coin_id SMALLINT NOT NULL REFERENCES coin(coin_id) ON DELETE CASCADE,
    PRIMARY KEY (name, coin_id)
);

-- 2. LIQUIDITY POOL TABLE
CREATE TABLE IF NOT EXISTS liquidity_pool (
    id SERIAL PRIMARY KEY,
    network VARCHAR(20) NOT NULL,
    protocol VARCHAR(20) NOT NULL,
    pool_name VARCHAR(255) NOT NULL,
    fee_tier VARCHAR(10),
    coin0_id SMALLINT NOT NULL REFERENCES coin(coin_id) ON DELETE CASCADE,
    coin1_id SMALLINT NOT NULL REFERENCES coin(coin_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    pool_address VARCHAR(42),
    pool_id VARCHAR(66),       -- V4 poolId (bytes32 hex); NULL for V2/V3
    reverted BOOLEAN DEFAULT FALSE,
    UNIQUE(network, protocol, pool_name)
);

CREATE INDEX IF NOT EXISTS idx_lp_pool_address ON liquidity_pool(pool_address);
CREATE INDEX IF NOT EXISTS idx_lp_pool_id ON liquidity_pool(pool_id);
CREATE INDEX IF NOT EXISTS idx_lp_coin0_id ON liquidity_pool(coin0_id);
CREATE INDEX IF NOT EXISTS idx_lp_coin1_id ON liquidity_pool(coin1_id);

-- 3. POSITION TABLE
CREATE TABLE IF NOT EXISTS liquidity_pool_position (
    id SERIAL PRIMARY KEY,
    pool_id INT REFERENCES liquidity_pool(id),
    position_key VARCHAR(100) NOT NULL UNIQUE,
    wallet_address VARCHAR(42) NOT NULL,
    token_id VARCHAR(50),
    tick_lower INTEGER,
    tick_upper INTEGER,
    price_lower NUMERIC,
    price_upper NUMERIC,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_lpp_wallet ON liquidity_pool_position(wallet_address);
CREATE INDEX IF NOT EXISTS idx_lpp_pool_id ON liquidity_pool_position(pool_id);

-- 4. SNAPSHOT TABLE
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot (
    id SERIAL,
    position_id INT REFERENCES liquidity_pool_position(id),
    timestamp TIMESTAMP NOT NULL,
    balance_usd NUMERIC,
    
    -- Flattened Assets (Corresponding to Pool Coin0/Coin1)
    coin0_amount NUMERIC,
    coin1_amount NUMERIC,

    -- Flattened Claimable (Unclaimed Rewards matching Pool Coins)
    coin0_claimable_amount NUMERIC,
    coin1_claimable_amount NUMERIC,
    
    -- Flattened Claimed (Cumulative collected fees matching Pool Coins)
    coin0_claimed_amount NUMERIC,
    coin1_claimed_amount NUMERIC,
    
    current_tick INTEGER,
    current_price NUMERIC,
    in_range BOOLEAN,
    
    -- Partition key must be part of the primary key
    PRIMARY KEY (timestamp, id)
) PARTITION BY RANGE (timestamp);

-- Monthly partitions for snapshots
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_01 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-01-01') TO ('2024-02-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_02 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-02-01') TO ('2024-03-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_03 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-03-01') TO ('2024-04-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_04 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-04-01') TO ('2024-05-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_05 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-05-01') TO ('2024-06-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_06 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-06-01') TO ('2024-07-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_07 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-07-01') TO ('2024-08-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_08 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-08-01') TO ('2024-09-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_09 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-09-01') TO ('2024-10-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_10 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-10-01') TO ('2024-11-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_11 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-11-01') TO ('2024-12-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2024_12 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2024-12-01') TO ('2025-01-01');

CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_01 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_02 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_03 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-03-01') TO ('2025-04-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_04 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_05 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_06 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-06-01') TO ('2025-07-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_07 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-07-01') TO ('2025-08-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_08 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-08-01') TO ('2025-09-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_09 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-09-01') TO ('2025-10-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_10 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-10-01') TO ('2025-11-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_11 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-11-01') TO ('2025-12-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2025_12 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');

CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_01 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_02 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_03 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_04 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_05 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_06 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_07 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_08 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_09 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_10 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_11 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_2026_12 PARTITION OF liquidity_pool_position_snapshot FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');

CREATE TABLE IF NOT EXISTS liquidity_pool_position_snapshot_default PARTITION OF liquidity_pool_position_snapshot DEFAULT;

CREATE INDEX IF NOT EXISTS idx_snapshot_pos_time ON liquidity_pool_position_snapshot(position_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_snapshot_time ON liquidity_pool_position_snapshot(timestamp DESC);

-- 4.5 LIQUIDITY POOL HISTORY TABLE
CREATE TABLE IF NOT EXISTS liquidity_pool_history (
    id SERIAL PRIMARY KEY,
    pool_id INTEGER REFERENCES liquidity_pool(id),
    date DATE NOT NULL,
    tx_count INTEGER DEFAULT 0,
    volume_usd NUMERIC DEFAULT 0,
    tvl_usd NUMERIC DEFAULT 0,
    UNIQUE(pool_id, date)
);
CREATE INDEX IF NOT EXISTS idx_lp_history_date ON liquidity_pool_history(date);
CREATE INDEX IF NOT EXISTS idx_lp_history_pool ON liquidity_pool_history(pool_id);

-- 5. UNISWAP V3 SWAPS (Existing table)
CREATE TABLE IF NOT EXISTS uniswap_v3_swaps (
    id VARCHAR(255) PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    tx_hash VARCHAR(66) NOT NULL,
    token0_address VARCHAR(42) NOT NULL,
    token1_address VARCHAR(42) NOT NULL,
    token0_symbol VARCHAR(100),
    token1_symbol VARCHAR(100),
    amount0 NUMERIC,
    amount1 NUMERIC,
    amount_usd NUMERIC,
    fee_tier VARCHAR(20),
    network VARCHAR(20) DEFAULT 'Ethereum',
    protocol VARCHAR(50) DEFAULT 'Uniswap V3'
);

CREATE INDEX IF NOT EXISTS idx_swaps_timestamp ON uniswap_v3_swaps(timestamp);
CREATE INDEX IF NOT EXISTS idx_swaps_token0 ON uniswap_v3_swaps(token0_symbol);
CREATE INDEX IF NOT EXISTS idx_swaps_token1 ON uniswap_v3_swaps(token1_symbol);
CREATE INDEX IF NOT EXISTS idx_swaps_network_timestamp ON uniswap_v3_swaps(network, timestamp);

-- 5.1 UNISWAP V4 SWAPS
CREATE TABLE IF NOT EXISTS uniswap_v4_swaps (
    id VARCHAR(255) PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    tx_hash VARCHAR(66) NOT NULL,
    token0_address VARCHAR(42) NOT NULL,
    token1_address VARCHAR(42) NOT NULL,
    token0_symbol VARCHAR(100),
    token1_symbol VARCHAR(100),
    amount0 NUMERIC,
    amount1 NUMERIC,
    amount_usd NUMERIC,
    fee_tier VARCHAR(20),
    network VARCHAR(20) DEFAULT 'Ethereum',
    protocol VARCHAR(50) DEFAULT 'Uniswap V4'
);

CREATE INDEX IF NOT EXISTS idx_v4_swaps_timestamp ON uniswap_v4_swaps(timestamp);
CREATE INDEX IF NOT EXISTS idx_v4_swaps_token0 ON uniswap_v4_swaps(token0_symbol);
CREATE INDEX IF NOT EXISTS idx_v4_swaps_token1 ON uniswap_v4_swaps(token1_symbol);
CREATE INDEX IF NOT EXISTS idx_v4_swaps_network_timestamp ON uniswap_v4_swaps(network, timestamp);

-- 5.2 UNISWAP V2 SWAPS
CREATE TABLE IF NOT EXISTS uniswap_v2_swaps (
    id VARCHAR(255) PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    tx_hash VARCHAR(66) NOT NULL,
    token0_address VARCHAR(42) NOT NULL,
    token1_address VARCHAR(42) NOT NULL,
    token0_symbol VARCHAR(255),
    token1_symbol VARCHAR(255),
    amount0 NUMERIC,
    amount1 NUMERIC,
    amount_usd NUMERIC,
    fee_tier VARCHAR(20) DEFAULT '0.30%',
    network VARCHAR(20) DEFAULT 'Ethereum',
    protocol VARCHAR(50) DEFAULT 'Uniswap V2'
);

CREATE INDEX IF NOT EXISTS idx_v2_swaps_timestamp ON uniswap_v2_swaps(timestamp);
CREATE INDEX IF NOT EXISTS idx_v2_swaps_token0 ON uniswap_v2_swaps(token0_symbol);
CREATE INDEX IF NOT EXISTS idx_v2_swaps_token1 ON uniswap_v2_swaps(token1_symbol);
CREATE INDEX IF NOT EXISTS idx_v2_swaps_network_timestamp ON uniswap_v2_swaps(network, timestamp);

-- 5.5 COIN PRICE HISTORY
CREATE TABLE IF NOT EXISTS coin_price_history (
    id SERIAL PRIMARY KEY,
    coin_id SMALLINT NOT NULL REFERENCES coin(coin_id) ON DELETE CASCADE,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    price NUMERIC NOT NULL,
    UNIQUE(coin_id, timestamp)
);
CREATE INDEX IF NOT EXISTS idx_cph_coin_id ON coin_price_history(coin_id);

-- 5.6 LIQUIDITY POOL POSITION EVENTS
CREATE TABLE IF NOT EXISTS liquidity_pool_position_event ( 
    id SERIAL PRIMARY KEY, 
    position_id INTEGER REFERENCES liquidity_pool_position(id), 
    tx_hash VARCHAR(66) NOT NULL, 
    block_number INTEGER NOT NULL, 
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL, 
    event_type VARCHAR(50) NOT NULL, 
    amount0 NUMERIC DEFAULT 0, 
    amount1 NUMERIC DEFAULT 0, 
    amount_usd NUMERIC DEFAULT 0, 
    liquidity_change NUMERIC, 
    tick_lower INTEGER, 
    tick_upper INTEGER, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    UNIQUE(position_id, tx_hash, event_type) 
); 
CREATE INDEX IF NOT EXISTS idx_lp_event_pos ON liquidity_pool_position_event(position_id); 
CREATE INDEX IF NOT EXISTS idx_lp_event_type ON liquidity_pool_position_event(event_type); 
CREATE INDEX IF NOT EXISTS idx_lp_event_ts ON liquidity_pool_position_event(timestamp);

-- 6. TRIGGERS
CREATE OR REPLACE FUNCTION enforce_uppercase_symbols() 
RETURNS TRIGGER AS $$
BEGIN
  -- Truncate to 10 chars first to respect schema
  NEW.symbol = LEFT(UPPER(NEW.symbol), 10);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_coin_upper 
BEFORE INSERT OR UPDATE ON coin
FOR EACH ROW EXECUTE FUNCTION enforce_uppercase_symbols();

-- 7. INITIAL DATA

INSERT INTO coin (symbol, hardness) VALUES
('ETH', 860),
('WETH', 860),
('USDC', 1000),
('USDT', 990),
('DAI', 970),
('WBTC', 870),
('EURC', 940),
('LINK', 850),
('UNI', 840),
('AAVE', 820),
('USDS', 980),
('GHO', 950),
('EURI', 920),
('STKAAVE', 800),
('RETH', 860),
('STETH', 860),
('WSTETH', 860),
('SOL', 700),
('MSOL', 700),
('PENDLE', 600),
('USDE', 980),
('STKGHO', 950),
('SGHO', 950),
('RLUSD', 980),
('SUSDS', 980),
('EURCV', 940),
('EURQ', 940),
('PAXG', 850),
('XAUT', 850),
('BTC', 900),
('CBBTC', 900),
('STAAVE', 800),
('CLAAVE', 800),
('MIM', 970),
('ENA', 500),
('USDC.E', 990),
('USDBC', 990),
('BTCB', 870),
('BUSD', 950),
('CAKE', 600),
('BETH', 860),
('FDUSD', 980),
('TUSD', 960),
('GMX', 650),
('ZRO', 680),
('WBNB', 800)
ON CONFLICT (symbol) DO UPDATE SET hardness = EXCLUDED.hardness;

INSERT INTO coin_contract (coin_id, chain, contract_address, is_native) VALUES
((SELECT coin_id FROM coin WHERE symbol='ETH'), 'ethereum', '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', TRUE),
((SELECT coin_id FROM coin WHERE symbol='WETH'), 'ethereum', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', FALSE),
((SELECT coin_id FROM coin WHERE symbol='USDC'), 'ethereum', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', FALSE),
((SELECT coin_id FROM coin WHERE symbol='USDT'), 'ethereum', '0xdac17f958d2ee523a2206206994597c13d831ec7', FALSE),
((SELECT coin_id FROM coin WHERE symbol='DAI'), 'ethereum', '0x6b175474e89094c44da98b954eedeac495271d0f', FALSE),
((SELECT coin_id FROM coin WHERE symbol='WBTC'), 'ethereum', '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599', FALSE),
((SELECT coin_id FROM coin WHERE symbol='EURC'), 'ethereum', '0x1abaea1f7c830f0654c721306e53a20516147924', FALSE),
((SELECT coin_id FROM coin WHERE symbol='LINK'), 'ethereum', '0x514910771af9ca656af840dff83e8264ecf986ca', FALSE),
((SELECT coin_id FROM coin WHERE symbol='UNI'), 'ethereum', '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984', FALSE),
((SELECT coin_id FROM coin WHERE symbol='AAVE'), 'ethereum', '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9', FALSE),
((SELECT coin_id FROM coin WHERE symbol='USDS'), 'ethereum', '0xd75003661288c1c39062eb185cd27962b9a78572', FALSE),
((SELECT coin_id FROM coin WHERE symbol='GHO'), 'ethereum', '0x40d1640030509618f3a3848bdf581d58023c721c', FALSE),
((SELECT coin_id FROM coin WHERE symbol='EURI'), 'ethereum', '0xf23351d4289cf30113a34a81b7e42be005232ba3', FALSE),
((SELECT coin_id FROM coin WHERE symbol='STKAAVE'), 'ethereum', '0x4da27a545c0c5b758a6ba100e3a078a959074b1e', FALSE),
((SELECT coin_id FROM coin WHERE symbol='RETH'), 'ethereum', '0xae78736cd615f374d3085123a210448e74fc6393', FALSE),
((SELECT coin_id FROM coin WHERE symbol='STETH'), 'ethereum', '0xae7ab96520de3a18e5e111b5eaab095312d7fe84', FALSE),
((SELECT coin_id FROM coin WHERE symbol='WSTETH'), 'ethereum', '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0', FALSE),
((SELECT coin_id FROM coin WHERE symbol='SOL'), 'ethereum', '0xdummy_sol', FALSE),
((SELECT coin_id FROM coin WHERE symbol='MSOL'), 'ethereum', '0xdummy_msol', FALSE),
((SELECT coin_id FROM coin WHERE symbol='PENDLE'), 'ethereum', '0x808507121b80c0546a1d48931130635e169fa121', FALSE),
((SELECT coin_id FROM coin WHERE symbol='USDE'), 'ethereum', '0x4c9edd5852cd14fe7183fdb42c274d2808b04a55', FALSE),
((SELECT coin_id FROM coin WHERE symbol='STKGHO'), 'ethereum', '0xdummy_stkgho', FALSE),
((SELECT coin_id FROM coin WHERE symbol='SGHO'), 'ethereum', '0xdummy_sgho', FALSE),
((SELECT coin_id FROM coin WHERE symbol='RLUSD'), 'ethereum', '0xdummy_rlusd', FALSE),
((SELECT coin_id FROM coin WHERE symbol='SUSDS'), 'ethereum', '0xdummy_susds', FALSE),
((SELECT coin_id FROM coin WHERE symbol='EURCV'), 'ethereum', '0xdummy_eurcv', FALSE),
((SELECT coin_id FROM coin WHERE symbol='EURQ'), 'ethereum', '0xdummy_eurq', FALSE),
((SELECT coin_id FROM coin WHERE symbol='PAXG'), 'ethereum', '0x45804880bdc05151523316d3a01ff660eacc9292', FALSE),
((SELECT coin_id FROM coin WHERE symbol='XAUT'), 'ethereum', '0x68749665e53399066df52a092dd62128b1bf1e6f', FALSE),
((SELECT coin_id FROM coin WHERE symbol='BTC'), 'ethereum', '0xdummy_btc', FALSE),
((SELECT coin_id FROM coin WHERE symbol='CBBTC'), 'ethereum', '0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf', FALSE),
((SELECT coin_id FROM coin WHERE symbol='STAAVE'), 'ethereum', '0xdummy_staave', FALSE),
((SELECT coin_id FROM coin WHERE symbol='CLAAVE'), 'ethereum', '0xdummy_claave', FALSE),
((SELECT coin_id FROM coin WHERE symbol='MIM'), 'ethereum', '0x99d1ed205117f739c49110052e42337777777777', FALSE),
((SELECT coin_id FROM coin WHERE symbol='ENA'), 'ethereum', '0x57e114b691db790c35207b2e685d4a43181e6061', FALSE),
-- Arbitrum Contracts
((SELECT coin_id FROM coin WHERE symbol='ETH'), 'arbitrum', '0x0000000000000000000000000000000000000000', TRUE),
((SELECT coin_id FROM coin WHERE symbol='USDC.E'), 'arbitrum', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8', FALSE),
((SELECT coin_id FROM coin WHERE symbol='USDC'), 'arbitrum', '0xaf88d065e77c8cc2239327c5edb3a432268e5831', FALSE),
((SELECT coin_id FROM coin WHERE symbol='WETH'), 'arbitrum', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', FALSE),
((SELECT coin_id FROM coin WHERE symbol='USDT'), 'arbitrum', '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9', FALSE),
((SELECT coin_id FROM coin WHERE symbol='WBTC'), 'arbitrum', '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f', FALSE),
((SELECT coin_id FROM coin WHERE symbol='DAI'), 'arbitrum', '0xda10009c55681e77d502082691d29f8fb095569f', FALSE),
((SELECT coin_id FROM coin WHERE symbol='LINK'), 'arbitrum', '0xf97f4df75117a78c1a5a0dbb814af92458539fb4', FALSE),
((SELECT coin_id FROM coin WHERE symbol='GMX'), 'arbitrum', '0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a', FALSE),
((SELECT coin_id FROM coin WHERE symbol='AAVE'), 'arbitrum', '0xba5ddd1f9d7f570dc94a51479a000e3bce967196', FALSE),
((SELECT coin_id FROM coin WHERE symbol='ZRO'), 'arbitrum', '0x6985884c4392d348587b19cb9eaaf157f13271cd', FALSE),
-- Base Contracts
((SELECT coin_id FROM coin WHERE symbol='ETH'), 'base', '0x0000000000000000000000000000000000000000', TRUE),
((SELECT coin_id FROM coin WHERE symbol='WETH'), 'base', '0x4200000000000000000000000000000000000006', FALSE),
((SELECT coin_id FROM coin WHERE symbol='USDC'), 'base', '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913', FALSE),
((SELECT coin_id FROM coin WHERE symbol='USDBC'), 'base', '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca', FALSE),
((SELECT coin_id FROM coin WHERE symbol='CBBTC'), 'base', '0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf', FALSE),
-- BNB/BSC Contracts
((SELECT coin_id FROM coin WHERE symbol='BNB'), 'bsc', '0x0000000000000000000000000000000000000000', TRUE),
((SELECT coin_id FROM coin WHERE symbol='WBNB'), 'bsc', '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c', FALSE),
((SELECT coin_id FROM coin WHERE symbol='USDC'), 'bsc', '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d', FALSE),
((SELECT coin_id FROM coin WHERE symbol='USDT'), 'bsc', '0x55d398326f99059ff775485246999027b3197955', FALSE),
((SELECT coin_id FROM coin WHERE symbol='BTCB'), 'bsc', '0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c', FALSE),
((SELECT coin_id FROM coin WHERE symbol='BUSD'), 'bsc', '0xe9e7cea3dedca5984780bafc599bd69add087d56', FALSE),
((SELECT coin_id FROM coin WHERE symbol='CAKE'), 'bsc', '0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82', FALSE),
((SELECT coin_id FROM coin WHERE symbol='BETH'), 'bsc', '0x25063237838e18f49999b541a61962c641914a81', FALSE),
((SELECT coin_id FROM coin WHERE symbol='FDUSD'), 'bsc', '0x3813e82e6f7098b9583fc0f33a962d02018b6803', FALSE),
((SELECT coin_id FROM coin WHERE symbol='TUSD'), 'bsc', '0x14016e85a25aeb13065688e4b4a6e8f5679bee99', FALSE),
((SELECT coin_id FROM coin WHERE symbol='ETH'), 'bsc', '0x2170ed0880ac9a755fd29b2688956bd959f933f8', FALSE)
ON CONFLICT (coin_id, chain) DO UPDATE SET contract_address = EXCLUDED.contract_address;

-- Populate coin_family with initial multi-coin families
INSERT INTO coin_family (name, coin_id) VALUES
('USD', (SELECT coin_id FROM coin WHERE symbol='USDC')),
('USD', (SELECT coin_id FROM coin WHERE symbol='USDT')),
('USD', (SELECT coin_id FROM coin WHERE symbol='USDS')),
('USD', (SELECT coin_id FROM coin WHERE symbol='DAI')),
('USD', (SELECT coin_id FROM coin WHERE symbol='USDE')),
('USD', (SELECT coin_id FROM coin WHERE symbol='GHO')),
('USD', (SELECT coin_id FROM coin WHERE symbol='STKGHO')),
('USD', (SELECT coin_id FROM coin WHERE symbol='SGHO')),
('USD', (SELECT coin_id FROM coin WHERE symbol='RLUSD')),
('USD', (SELECT coin_id FROM coin WHERE symbol='SUSDS')),
('EUR', (SELECT coin_id FROM coin WHERE symbol='EURC')),
('EUR', (SELECT coin_id FROM coin WHERE symbol='EURCV')),
('EUR', (SELECT coin_id FROM coin WHERE symbol='EURI')),
('EUR', (SELECT coin_id FROM coin WHERE symbol='EURQ')),
('GOLD', (SELECT coin_id FROM coin WHERE symbol='PAXG')),
('GOLD', (SELECT coin_id FROM coin WHERE symbol='XAUT')),
('BTC', (SELECT coin_id FROM coin WHERE symbol='BTC')),
('BTC', (SELECT coin_id FROM coin WHERE symbol='WBTC')),
('BTC', (SELECT coin_id FROM coin WHERE symbol='CBBTC')),
('ETH', (SELECT coin_id FROM coin WHERE symbol='ETH')),
('ETH', (SELECT coin_id FROM coin WHERE symbol='WETH')),
('ETH', (SELECT coin_id FROM coin WHERE symbol='STETH')),
('ETH', (SELECT coin_id FROM coin WHERE symbol='WSTETH')),
('AAVE', (SELECT coin_id FROM coin WHERE symbol='AAVE')),
('AAVE', (SELECT coin_id FROM coin WHERE symbol='STAAVE')),
('AAVE', (SELECT coin_id FROM coin WHERE symbol='STKAAVE')),
('AAVE', (SELECT coin_id FROM coin WHERE symbol='CLAAVE'))
ON CONFLICT DO NOTHING;

-- 8. BACKWARD COMPATIBILITY VIEWS
CREATE OR REPLACE VIEW v_lp_snapshots_summary AS
SELECT 
    s.id,
    s.timestamp,
    pos.wallet_address AS address,
    pos.position_key,
    pool.protocol,
    pool.network,
    CASE 
        WHEN pos.token_id IS NOT NULL THEN pool.pool_name || ' (Token ID: ' || pos.token_id || ')' 
        ELSE pool.pool_name 
    END AS position_label,
    s.balance_usd,
    
    -- Reconstruct Assets
    c0.symbol as asset0_symbol,
    s.coin0_amount as asset0_amount,
    COALESCE(s.coin0_usd, 0) as asset0_usd, 
    c1.symbol as asset1_symbol,
    s.coin1_amount as asset1_amount,
    COALESCE(s.coin1_usd, 0) as asset1_usd,
    
    -- Reconstruct Rewards (Use Claimable Columns)
    c0.symbol as reward0_symbol,
    s.coin0_claimable_amount as reward0_amount,
    COALESCE(s.coin0_claimable_usd, 0) as reward0_usd,
    c1.symbol as reward1_symbol,
    s.coin1_claimable_amount as reward1_amount,
    COALESCE(s.coin1_claimable_usd, 0) as reward1_usd,

    -- Reconstruct JSONs for legacy app
    jsonb_build_array(
        jsonb_build_object('symbol', c0.symbol, 'balance', s.coin0_amount, 'balanceUSD', COALESCE(s.coin0_usd, 0)),
        jsonb_build_object('symbol', c1.symbol, 'balance', s.coin1_amount, 'balanceUSD', COALESCE(s.coin1_usd, 0))
    ) as assets,
    
    jsonb_build_array(
        jsonb_build_object('symbol', c0.symbol, 'balance', s.coin0_claimable_amount, 'balanceUSD', COALESCE(s.coin0_claimable_usd, 0)),
        jsonb_build_object('symbol', c1.symbol, 'balance', s.coin1_claimable_amount, 'balanceUSD', COALESCE(s.coin1_claimable_usd, 0))
    ) as unclaimed,
     
    -- Images (From Coins)
    jsonb_build_array(
        c0.image_url,
        c1.image_url
    ) as images,
    
    -- Total unclaimed (Approximation, no USD value stored yet)
    COALESCE(s.coin0_claimable_usd, 0) + COALESCE(s.coin1_claimable_usd, 0) as total_unclaimed_usd,
    
    -- Range data
    pos.token_id,
    pos.tick_lower,
    pos.tick_upper,
    s.current_tick,
    pos.price_lower,
    pos.price_upper,
    s.current_price,
    s.in_range,
    pool.fee_tier,
    s.coin0_claimed_amount,
    s.coin1_claimed_amount
FROM liquidity_pool_position_snapshot s
JOIN liquidity_pool_position pos ON s.position_id = pos.id
JOIN liquidity_pool pool ON pos.pool_id = pool.id
JOIN coin c0 ON pool.coin0_id = c0.coin_id
JOIN coin c1 ON pool.coin1_id = c1.coin_id;
