-- ============================================================================
-- SQL Migration: Multi-Chain Coin Table Redesign (Phase 1 & 2 & 3)
-- Run via:
--   psql "$DATA_WAREHOUSE_DB" -f migrate_coin_v2.sql
-- ============================================================================

-- Start transaction
BEGIN;

-- 1. Drop the backward compatibility view first
DROP VIEW IF EXISTS v_lp_snapshots_summary;

-- 2. Drop existing foreign key constraints that reference the coin table
ALTER TABLE coin_family DROP CONSTRAINT IF EXISTS coin_family_symbol_fkey;
ALTER TABLE liquidity_pool DROP CONSTRAINT IF EXISTS liquidity_pool_coin0_symbol_fkey;
ALTER TABLE liquidity_pool DROP CONSTRAINT IF EXISTS liquidity_pool_coin1_symbol_fkey;
ALTER TABLE coin_price_history DROP CONSTRAINT IF EXISTS coin_price_history_address_fkey;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'swaps') THEN
        ALTER TABLE swaps DROP CONSTRAINT IF EXISTS swaps_t0_coin_id_fkey;
        ALTER TABLE swaps DROP CONSTRAINT IF EXISTS swaps_t1_coin_id_fkey;
    END IF;
END $$;

-- 3. Drop primary key constraint on coin table (currently symbol)
ALTER TABLE coin DROP CONSTRAINT IF EXISTS coin_pkey CASCADE;

-- 4. Re-widen symbol fields in referencing tables to VARCHAR(10) to support USDC.E, etc.
ALTER TABLE coin ALTER COLUMN symbol TYPE VARCHAR(10);
ALTER TABLE coin_family ALTER COLUMN symbol TYPE VARCHAR(10);
ALTER TABLE liquidity_pool ALTER COLUMN coin0_symbol TYPE VARCHAR(10);
ALTER TABLE liquidity_pool ALTER COLUMN coin1_symbol TYPE VARCHAR(10);

-- 5. Prepare coin_id in coin table
-- Check if coin_id exists. If not, add it as serial/identity. If it does, we will reuse it.
-- We do this by checking column existence and altering it to identity/primary key.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='coin' AND column_name='coin_id') THEN
        ALTER TABLE coin ADD COLUMN coin_id SMALLINT GENERATED BY DEFAULT AS IDENTITY;
    ELSE
        -- Ensure type is SMALLINT (widening if needed or matching our target size)
        ALTER TABLE coin ALTER COLUMN coin_id TYPE SMALLINT;
        -- If it was a serial sequence, drop sequence association so we can use identity
        ALTER TABLE coin ALTER COLUMN coin_id DROP DEFAULT;
        ALTER TABLE coin ALTER COLUMN coin_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- Set coin_id as PRIMARY KEY
ALTER TABLE coin ADD CONSTRAINT coin_pkey PRIMARY KEY (coin_id);
ALTER TABLE coin ADD CONSTRAINT uq_coin_symbol UNIQUE (symbol);

-- 6. Create the coin_contract table
CREATE TABLE IF NOT EXISTS coin_contract (
    coin_id SMALLINT NOT NULL REFERENCES coin(coin_id) ON DELETE CASCADE,
    chain VARCHAR(20) NOT NULL,
    contract_address VARCHAR(64) NOT NULL,
    decimals INTEGER DEFAULT 18,
    is_native BOOLEAN DEFAULT FALSE,
    verified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (coin_id, chain)
);

-- Indexes for fast lookups
CREATE UNIQUE INDEX IF NOT EXISTS idx_coin_contract_addr ON coin_contract (chain, LOWER(contract_address));
CREATE INDEX IF NOT EXISTS idx_coin_contract_chain ON coin_contract (chain);

-- 7. Add foreign key columns to dependent tables
ALTER TABLE coin_family ADD COLUMN IF NOT EXISTS coin_id SMALLINT;
ALTER TABLE coin_price_history ADD COLUMN IF NOT EXISTS coin_id SMALLINT;

ALTER TABLE liquidity_pool ADD COLUMN IF NOT EXISTS coin0_id SMALLINT;
ALTER TABLE liquidity_pool ADD COLUMN IF NOT EXISTS coin1_id SMALLINT;

-- 8. Data Migration & Backfill
-- Populating coin_contract from current ethereum_address
INSERT INTO coin_contract (coin_id, chain, contract_address, decimals, is_native, verified_at)
SELECT coin_id, 'ethereum', ethereum_address, decimals, (symbol = 'ETH'), NOW()
FROM coin
WHERE ethereum_address IS NOT NULL
ON CONFLICT (coin_id, chain) DO UPDATE SET
    contract_address = EXCLUDED.contract_address,
    decimals = COALESCE(EXCLUDED.decimals, coin_contract.decimals),
    verified_at = EXCLUDED.verified_at;

-- Populate coin_id in coin_family
UPDATE coin_family cf
SET coin_id = c.coin_id
FROM coin c
WHERE cf.symbol = c.symbol;

-- Populate coin_id in coin_price_history
UPDATE coin_price_history cph
SET coin_id = c.coin_id
FROM coin c
WHERE cph.symbol = c.symbol;

-- Populate coin0_id and coin1_id in liquidity_pool
UPDATE liquidity_pool lp
SET coin0_id = c0.coin_id
FROM coin c0
WHERE lp.coin0_symbol = c0.symbol;

UPDATE liquidity_pool lp
SET coin1_id = c1.coin_id
FROM coin c1
WHERE lp.coin1_symbol = c1.symbol;

-- 9. Enforce NOT NULL constraints & Foreign Keys
ALTER TABLE coin_family ALTER COLUMN coin_id SET NOT NULL;
ALTER TABLE coin_family ADD CONSTRAINT fk_coin_family_coin_id FOREIGN KEY (coin_id) REFERENCES coin(coin_id) ON DELETE CASCADE;

-- Recreate primary key for coin_family using (name, coin_id)
ALTER TABLE coin_family DROP CONSTRAINT IF EXISTS coin_family_pkey;
ALTER TABLE coin_family ADD CONSTRAINT coin_family_pkey PRIMARY KEY (name, coin_id);

-- Enforce coin_id on coin_price_history
ALTER TABLE coin_price_history ALTER COLUMN coin_id SET NOT NULL;
ALTER TABLE coin_price_history ADD CONSTRAINT fk_cph_coin_id FOREIGN KEY (coin_id) REFERENCES coin(coin_id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_cph_coin_id ON coin_price_history (coin_id);

-- Enforce coin0_id/coin1_id on liquidity_pool
-- Delete pools where coins could not be resolved (unresolved orphan records)
DELETE FROM liquidity_pool WHERE coin0_id IS NULL OR coin1_id IS NULL;

ALTER TABLE liquidity_pool ALTER COLUMN coin0_id SET NOT NULL;
ALTER TABLE liquidity_pool ALTER COLUMN coin1_id SET NOT NULL;
ALTER TABLE liquidity_pool ADD CONSTRAINT fk_lp_coin0 FOREIGN KEY (coin0_id) REFERENCES coin(coin_id) ON DELETE CASCADE;
ALTER TABLE liquidity_pool ADD CONSTRAINT fk_lp_coin1 FOREIGN KEY (coin1_id) REFERENCES coin(coin_id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_lp_coin0_id ON liquidity_pool(coin0_id);
CREATE INDEX IF NOT EXISTS idx_lp_coin1_id ON liquidity_pool(coin1_id);

-- Restore swaps table FKs
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'swaps') THEN
        ALTER TABLE swaps ADD CONSTRAINT swaps_t0_coin_id_fkey FOREIGN KEY (t0_coin_id) REFERENCES coin(coin_id);
        ALTER TABLE swaps ADD CONSTRAINT swaps_t1_coin_id_fkey FOREIGN KEY (t1_coin_id) REFERENCES coin(coin_id);
    END IF;
END $$;

-- 10. Clean up deprecated column references
-- Drop ethereum_address from coin
ALTER TABLE coin DROP COLUMN IF EXISTS ethereum_address CASCADE;

-- Drop symbol from coin_family
ALTER TABLE coin_family DROP COLUMN IF EXISTS symbol CASCADE;

-- Drop coin0_symbol/coin1_symbol from liquidity_pool
ALTER TABLE liquidity_pool DROP COLUMN IF EXISTS coin0_symbol CASCADE;
ALTER TABLE liquidity_pool DROP COLUMN IF EXISTS coin1_symbol CASCADE;

-- Drop symbol and address from coin_price_history
ALTER TABLE coin_price_history DROP COLUMN IF EXISTS symbol CASCADE;
ALTER TABLE coin_price_history DROP COLUMN IF EXISTS address CASCADE;

-- 11. Recreate the backward compatibility view v_lp_snapshots_summary
CREATE OR REPLACE VIEW v_lp_snapshots_summary AS
SELECT 
    s.id,
    s.timestamp,
    pos.wallet_address AS address,
    pos.position_key,
    pool.protocol,
    pool.network,
    CASE 
        WHEN pos.token_id IS NOT NULL THEN pool.pool_name || ' (Token ID: ' || pos.token_id || ')' 
        ELSE pool.pool_name 
    END AS position_label,
    s.balance_usd,
    
    -- Reconstruct Assets using coin table JOINs
    c0.symbol as asset0_symbol,
    s.coin0_amount as asset0_amount,
    0 as asset0_usd, 
    c1.symbol as asset1_symbol,
    s.coin1_amount as asset1_amount,
    0 as asset1_usd,
    
    -- Reconstruct Rewards using coin table JOINs
    c0.symbol as reward0_symbol,
    s.coin0_claimable_amount as reward0_amount,
    0 as reward0_usd,
    c1.symbol as reward1_symbol,
    s.coin1_claimable_amount as reward1_amount,
    0 as reward1_usd,

    -- Reconstruct JSONs for legacy app
    jsonb_build_array(
        jsonb_build_object('symbol', c0.symbol, 'balance', s.coin0_amount, 'balanceUSD', 0),
        jsonb_build_object('symbol', c1.symbol, 'balance', s.coin1_amount, 'balanceUSD', 0)
    ) as assets,
    
    jsonb_build_array(
        jsonb_build_object('symbol', c0.symbol, 'balance', s.coin0_claimable_amount, 'balanceUSD', 0),
        jsonb_build_object('symbol', c1.symbol, 'balance', s.coin1_claimable_amount, 'balanceUSD', 0)
    ) as unclaimed,
     
    -- Images (From Coins)
    jsonb_build_array(
        c0.image_url,
        c1.image_url
    ) as images,
    
    -- Total unclaimed (Approximation, no USD value stored yet)
    0 as total_unclaimed_usd,
    
    -- Range data
    pos.token_id,
    pos.tick_lower,
    pos.tick_upper,
    s.current_tick,
    pos.price_lower,
    pos.price_upper,
    s.current_price,
    s.in_range,
    pool.fee_tier,
    s.coin0_claimed_amount,
    s.coin1_claimed_amount
FROM liquidity_pool_position_snapshot s
JOIN liquidity_pool_position pos ON s.position_id = pos.id
JOIN liquidity_pool pool ON pos.pool_id = pool.id
JOIN coin c0 ON pool.coin0_id = c0.coin_id
JOIN coin c1 ON pool.coin1_id = c1.coin_id;

-- Commit transaction
COMMIT;
