coin-families:
  - name: ETH
    correlated: true
    coin-list:
      - ETH
      - WETH
      - BETH
      - WBETH
      - STETH
      - WSTETH
      - RETH
      - RSETH
      - METH
      - LSETH
      - EZETH
      - ETHX
      - TETH
      - ETH+
      - OETH
      - SWETH
      - AGETH
      - VBETH
      - ROCK.RETH
      - ANKRETH
      - NETH
      - ETHA
      - YNETHX
      - CRVSTETH
      - ETH0
      - ATETH
      - CBETH
      - GTETH
      - EZETH
      - AETHWETH
      - aEthwstE
      - aEthcbE
      - aEthrETH
      - aArbWETH
      - aArbwstE
      - aBasWETH
      - aBascbE
      - aBaswstE
      - aPolWETH
      - mcWETH
      - mwstETH
      - mBasWETH
      - mBascbE
      - mweETH
      - mezETH
      - mBasweE
      - mArbWETH
      - mArbwstE
      - crvSTETH
      - crvWSTE
      - crvRETH
      - crvFRXE
      - sFRXETH
      - fWETH
      - fwstETH
      - fweETH
      - fcbETH
      - fBasWETH
      - fArbWETH
      - cWETHv3
      - cArbWETH
      - cBasWETH
      - cPolWETH
      - cETH
      - spWETH
      - spwstE
      - sprETH
      - PTeETH
      - PTezETH
      - PTwstE
      - vETH
      - weETH
      - EETH
      - USDT0
  - name: USD
    correlated: true
    coin-list:
      - USDC
      - USDT
      - DAI
      - USDS
      - sUSDS
      - USD1
      - BUIDL
      - sGHO
      - STKGHO
      - USDf
      - USD0
      - TUSD
      - USDE
      - GHO
      - YLDS
      - RLUSD
      - SUSDS
      - FDUSD
      - CRVUSD
      - sCRVUSD
      - sUSDe
      - BUSD
      - AUSD
      - FRAX
      - FLEXUSD
      - FRXUSD
      - NUSD
      - GUSD
      - USDP
      - BOLD
      - USDCV
      - MUSD
      - PYUSD
      - syrupUSDC
      - AETHUSDT
      - AETHUSDC
      - aEthDAI
      - aEthPYUS
      - aEthFRAX
      - aEthGHO
      - aArbUSDC
      - aArbUSDT
      - aBasUSDC
      - aPolUSDC
      - aPolUSDT
      - aOptUSDC
      - mcUSDC
      - mUSDT
      - mPYUSD
      - mUSDe
      - msUSDe
      - mBasUSDC
      - maUSDC
      - mBasUSDT
      - mArbUSDC
      - mArbUSDT
      - crvUSD
      - crv3cryp
      - crvUSDC
      - crvUSDT
      - crvUSDS
      - fUSDC
      - fUSDT
      - fUSDe
      - fsUSDe
      - fGHO
      - fBasUSDC
      - fArbUSDC
      - cUSDCv3
      - cUSDTv3
      - cArbUSDC
      - cBasUSDC
      - cPolUSDC
      - cOptUSDC
      - cUSDC
      - cUSDT
      - CDAI
      - sDAI
      - spUSDC
      - spUSDT
      - spGHO
      - USDY
      - OUSG
      - rOUSG
      - USDYArb
      - PTsUSDe
      - PTUSDe
      - PTUSDC
      - sUSDf
      - vUSDC
      - vUSDT
      - vDAI
      - DOLA
    regexp-rule: ".*USD.*"

  - name: EUR
    correlated: true
    coin-list:
      - EURC
      - EURI
      - EURCV
      - EURQ
      - EURR
      - CEUR
      - DEURO
      - EEUR
      - EURA
      - EUROP
      - WERC
      - REUR
      - mBasEURC
      - crvEURC
  - name: BTC
    correlated: true
    coin-list:
      - BTC
      - WBTC
      - CBBTC
      - tBTC
      - FBTC
      - LBTC
      - kBTC
      - aEthWBTC
      - aEthtBTC
      - aArbWBTC
      - mWBTC
      - mBascbBT
      - mtBTC
      - mArbWBTC
      - crvrenBT
      - crvCBBT
      - fWBTC
      - fcbBTC
      - cWBTC
      - vBTC
  - name: GOLD
    correlated: true
    coin-list:
      - PAXG
      - XAUT
      - GSX
      - GLDX
      - IAUon
      - XAUM
      - XAUT0



  - name: SILVER
    correlated: true
    coin-list:
      - SLVon
      - SLVx
      - SLV
  
  - name: STOCK
    correlated: false
    coin-list:
      - SPYon
      - SPYx
      - QQQx
      - INTLCx
      - TSLAx
      - HOODx
      - GOOGLx
      - NVDAx
      - CRCLx
      - AAPLx
      - MSFTx
      - METAx
      - VTx
      - COINx
      - KOx
      - IEMGx
      - MAx
      - AZNx
      - PFEx
      - PGx 
      - Vx 
      - NLRx 
      - JNJx
      - CRCLon
      - NVDAOn
      - QQQon
      - HIMSon
      - INTCon
      - TSLon
      - IEFAon
      - SPCXon
      - TSMon
      - IEMGon
      - AMDon
      - AAPLon
      - AMZon
      - METAon
      - IWNon
      - ASMLon
      - BMNRon 
  
  - name: SOL
    correlated: true
    coin-list:
      - SOL
      - mSOL

  - name: AAVE
    correlated: true
    coin-list:
      - AAVE
      - STKAAVE

  - name: BNB
    correlated: true
    coin-list:
      - BNB
      - WBNB

  - name: Tier1
    correlated: false
    sql-rule: "cmc_rank < 100"
    include-coin:
      - PENDLE 
      - ENA